# Generated by Django 4.1.1 on 2022-09-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firn', '0005_alter_item_imagem_alter_item_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
    ]
