# Generated by Django 4.1.1 on 2022-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firn', '0006_remove_item_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
