# Generated by Django 4.1.1 on 2022-09-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firn', '0007_item_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imagem',
        ),
    ]
