# Generated by Django 4.1.1 on 2022-09-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firn', '0010_alter_item_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.TextField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('descricao', models.TextField(blank=True, default=None, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firn.item')),
            ],
        ),
    ]
